#!/bin/sh

# This program starts up all the 3080 docker subscripts!

./docker_run.bash -c ./config/3080/amazon_rtx_3080.yaml -a discord -w https://discordapp.com/api/webhooks/
./docker_run.bash -c ./config/3080/bestbuy_rtx_3080.yaml -a discord -w https://discordapp.com/api/webhooks/
./docker_run.bash -c ./config/3080/bhphoto_rtx_3080.yaml -a discord -w https://discordapp.com/api/webhooks/
./docker_run.bash -c ./config/3080/microcenter_rtx_3080.yaml -a discord -w https://discordapp.com/api/webhooks/
./docker_run.bash -c ./config/3080/newegg_rtx_3080.yaml -a discord -w https://discordapp.com/api/webhooks/
